#! /usr/bin/env python3
from argparse import ArgumentParser
from pathlib import Path
import re

def main():
    parser = ArgumentParser()
    parser.add_argument('--chat', required=True, type=str, help='File path to exported WhatsApp chat as .txt file.')
    # TODO: make the timestamp format less strict
    parser.add_argument("--start_date", required=True, type=str, help="Start date to being parsing stats (format: m/dd/yy).")
    args = parser.parse_args()

    # iterate through lines of the file until we find the target start date
    # once we've found the start date, then we begin counting statistics
    found_start = False
    unique_senders = set()
    num_msgs = 0

    chat_file = open(Path(args.chat))
    for line in chat_file:
        # lines that begin a new message should begin with a timestamp in this format
        # full regular expression: ^([\d]*)[\/]([\d]*)[\/]([\d]*), [\d]*:[\d]* (AM|PM)
        # we only need the date portion to match the target date
        timestamp = re.search("^([\d]*)[\/]([\d]*)[\/]([\d]*)", line)
        if not timestamp:
            continue
    
        # check if the line has our target date if we haven't found it yet
        if timestamp.group(0) == args.start_date:
            found_start = True;
        
        if not found_start:
            continue
        
        # at this point, we'll begin parsing the messages for stats

        # to get the sender, remove the date from the beginning of the line
        # then, match any character up to the colon
        parseline = re.sub("^([\d]*)[\/]([\d]*)[\/]([\d]*), [\d]*:[\d]* (AM|PM) - ", "", line)
        sender = re.search("^([^:])+:", parseline)

        # messages such as people joining the chat don't have senders
        # we don't want to count them either, so increment num_msgs later
        if not sender:
            continue

        unique_senders.add(sender.group(0))
        num_msgs += 1

    print("RESULTS:")
    print("Unique senders: " + str(len(unique_senders)))
    print("Number of messages: " + str(num_msgs))

if __name__ == '__main__':
    main()